const REGISTER_USER = "REGISTER_USER";
const REPOS_REQUEST = "REPOS_REQUEST";
const REPOS_REQUEST_SUCESSFUL = "REPOS_REQUEST_SUCESSFUL";
const REPOS_REQUEST_FAILURE = "REPOS_REQUEST_FAILURE";
const LOGOUT = "LOGOUT";

export {
  REGISTER_USER,
  REPOS_REQUEST,
  REPOS_REQUEST_SUCESSFUL,
  REPOS_REQUEST_FAILURE, 
  LOGOUT
}
